# Base configs
baseurl: "/PhotoGallery"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Yi Zhang"
subtitle: "Just things I love"
author: "Yi Zhang"
header:
 title: "Photography"
 subtitle: "by Yi Zhang"
footer:
 name: "Hey there, my name is Yi Zhang"
 bio: "Do not need one."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this  on github</a> ;)"
web_design: "AJ"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ram__patra"
#  instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://github.com/YiZhangCUG"
